name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
    example-job:
        runs-on: ubuntu-latest
        steps:
          - name: Check out the repository to the runner
            uses: actions/checkout@v4  
          - name: Run a script
            run: |
                wget https://raw.githubusercontent.com/htilssu-huflit/github_action/main/google-services.json 
                echo ${{ vars}}
                ls -la